# Travis CI configuration

language: node_js

node_js:
  - "9.0.0"

services:
  - docker

# Building docker image
before_install:
  - docker build -t clientresponse-demo .

# Verifying server.js for syntax errors, .js
# and .json files for style, using eslint
script:
  - node --check server/server.js
  - npm i -g eslint eslint-plugin-react babel-eslint eslint-plugin-json
  - eslint --ext .json .js server client/src

cache:
  directories:
    - node_modules
